# Generated by Django 3.2.3 on 2021-06-13 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url_shortener', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shortener',
            options={'ordering': ['-created']},
        ),
        migrations.RenameField(
            model_name='shortener',
            old_name='url_long',
            new_name='long_url',
        ),
        migrations.RemoveField(
            model_name='shortener',
            name='url_short',
        ),
        migrations.AddField(
            model_name='shortener',
            name='short_url',
            field=models.CharField(blank=True, max_length=15, unique=True),
        ),
        migrations.AddField(
            model_name='shortener',
            name='times_followed',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
